name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate"
dev = "npx prisma migrate deploy && PORT=4000 npm exec remix vite:dev"

[env]
PORT = "4000"
SHOPIFY_APP_URL = "https://shopify.droppin-eg.com"
